# Firebase Hosting deploy workflow — static site, no build
# Request ID: deploy-${{ github.run_id }}-${{ github.run_attempt }}

name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  deploy_static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log deploy context
        run: |
          echo "Deploying HopeSpark-Projec to Firebase Hosting"
          echo "Commit: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Request ID: deploy-${{ github.run_id }}-${{ github.run_attempt }}"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOPE_SPARK_DIGITAL }}
          channelId: live
          projectId: hope-spark-digital